export const vCardFields = [
  {
    id: "1",
    name: "title",
    type: "text",
    label: "Title",
    options: ["Mr.", "Ms.", "Dr.", "Prof."],
  },
  {
    id: "2",
    name: "firstName",
    type: "text",
    label: "First Name",
    required: true,
  },
  { id: "3", name: "middleName", type: "text", label: "Middle Name" },
  {
    id: "4",
    name: "lastName",
    type: "text",
    label: "Last Name",
    required: true,
  },
  {
    id: "5",
    name: "gender",
    type: "text",
    label: "Gender",
    options: ["Male", "Female", "Other"],
  },
  { id: "6", name: "email", type: "email", label: "Email" },
  { id: "7", name: "phone", type: "tel", label: "Phone" },
  { id: "8", name: "street", type: "text", label: "Street" },
  { id: "9", name: "city", type: "text", label: "City" },
  { id: "10", name: "state", type: "text", label: "State" },
  { id: "11", name: "country", type: "text", label: "Country" },
  { id: "12", name: "postalCode", type: "number", label: "Postal Code" },
  { id: "13", name: "birthday", type: "date", label: "Birthday" },
  { id: "14", name: "org", type: "text", label: "Organization" },
  { id: "15", name: "photoUrl", type: "url", label: "Photo URL" },
  { id: "16", name: "website", type: "url", label: "Website" },
  { id: "17", name: "instagram", type: "url", label: "Instagram" },
  { id: "18", name: "linkedin", type: "url", label: "LinkedIn" },
  { id: "19", name: "twitter", type: "url", label: "Twitter" },
  { id: "20", name: "facebook", type: "url", label: "Facebook" },
  { id: "21", name: "note", type: "textarea", label: "Note" },
];
