export const vCardFields = [
  { name: "firstName", type: "text", label: "First Name", required: true },
  { name: "lastName", type: "text", label: "Last Name", required: true },
  { name: "middleName", type: "text", label: "Middle Name" },
  { name: "prefix", type: "text", label: "Prefix" },
  { name: "suffix", type: "text", label: "Suffix" },
  { name: "nickname", type: "text", label: "Nickname" },
  { name: "email", type: "email", label: "Email" },
  { name: "phone", type: "tel", label: "Phone" },
  { name: "homePhone", type: "tel", label: "Home Phone" },
  { name: "workPhone", type: "tel", label: "Work Phone" },
  { name: "cellPhone", type: "tel", label: "Cell Phone" },
  { name: "fax", type: "tel", label: "Fax" },
  { name: "org", type: "text", label: "Organization" },
  { name: "title", type: "text", label: "Title" },
  { name: "street", type: "text", label: "Street" },
  { name: "city", type: "text", label: "City" },
  { name: "state", type: "text", label: "State" },
  { name: "country", type: "text", label: "Country" },
  { name: "postalCode", type: "text", label: "Postal Code" },
  { name: "website", type: "url", label: "Website" },
  { name: "birthday", type: "date", label: "Birthday" },
  { name: "photoUrl", type: "url", label: "Photo URL" },
  { name: "gender", type: "text", label: "Gender" },
  { name: "timezone", type: "text", label: "Timezone" },
  { name: "note", type: "textarea", label: "Note" },
];
