export const vCardFields = [
  {
    name: "title",
    type: "text",
    label: "Title",
    options: ["Mr.", "Ms.", "Dr.", "Prof."],
  },
  { name: "firstName", type: "text", label: "First Name", required: true },
  { name: "middleName", type: "text", label: "Middle Name" },
  { name: "lastName", type: "text", label: "Last Name", required: true },
  {
    name: "gender",
    type: "text",
    label: "Gender",
    options: ["Male", "Female", "Other"],
  },
  { name: "email", type: "email", label: "Email" },
  { name: "phone", type: "tel", label: "Phone" },
  { name: "street", type: "text", label: "Street" },
  { name: "city", type: "text", label: "City" },
  { name: "state", type: "text", label: "State" },
  { name: "country", type: "text", label: "Country" },
  { name: "postalCode", type: "number", label: "Postal Code" },
  { name: "birthday", type: "date", label: "Birthday" },
  { name: "org", type: "text", label: "Organization" },
  { name: "photoUrl", type: "url", label: "Photo URL" },
  { name: "website", type: "url", label: "Website" },
  { name: "instagram", type: "url", label: "Instagram" },
  { name: "linkedin", type: "url", label: "LinkedIn" },
  { name: "twitter", type: "url", label: "Twitter" },
  { name: "facebook", type: "url", label: "Facebook" },
  { name: "note", type: "textarea", label: "Note" },
];
